production:
    smokehost: smoke.mybigu.edu
    smokeport: 443
    proxyhost: smoke.mybigu.edu
    proxyport: 4223
    
development:
    smokehost: localhost
    smokeport: 80
    proxyhost: localhost
    proxyport: 80
    
test:
    smokehost: localhost
    smokeport: 80
    proxyhost: localhost
    proxyport: 80